language: node_js
node_js:
  - "8"
script:
  - npm run lint
  - npm run test
  - npm run build 
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $token
  on:
    branch: master

